### ISSUE TITLE
p=NA from the interactionR_table

### ISSUE THREAD

**Issue by Wenxin-Wan** [epi-zen/interactionR#10]
Hi,

Great package. While using the interactionR_table command to produce the output table, p=NA was found for RERI, AP, and SI. Some ORs also have p.value = 0. I was wondering if there is any issue in producing those p.values? I tried both interactionR() and interactionR_boot and got the same outcomes.

Many thanks

**Comment by epi-zen** [comment]
Hi,

Currently, the package can only produce pvalues for RERI, AP, & SI when Delta method is the chosen method. For bootstrapping or 'MOVER' it cannot compute pvalues so it outputs NA. Hope that helps.

**Comment by Wenxin-Wan** [comment]
> 

Thank you very much! This is very helpful :) 

Best wishes
