### ISSUE TITLE
boostrap

### ISSUE THREAD

**Issue by jddly** [epi-zen/interactionR#5]
Hello there
Thank you very much for the package and code.
It is much helpful.

I am a R beginner and using the R4.1.2 version.
It went well using the example 1. But,
I met some problem in the boostrap using the code that you have kindly preprared.
My code is as follows;
--------------------------------------------------------------------------
library (interactionR)
data (cases)
## fit the interaction model
M2=glm <- glm(care ~ isi3*CC, family = binomial(link = "logit"), data = cases)
table_object2 = interactionR_boot(M2, ci.level = 0.95, em = F, recode = F, seed = 12345, s = 1000)
Loading required namespace: boot
interactionR_table(table_object)
-----------------------------------------------------------------------------
However,  the R kept told me 
"Loading required namespace: boot
**Error: unexpected symbol in "Loading required".**
I thought it was a sepelling mistake and might caused by some space.
Still it does not work.

So, I am writing to inquire about how shoul I fix this issue?
Anticipating to hearing from you.

Many thanks

**Comment by epi-zen** [comment]
Hi,

I am not sure how to replicate your error, but I don't think it is due to the package. Because the following codes work just fine: 

```
library(interactionR)

m <- glm(h ~ ns * smk,
         family = binomial(link = "logit"),
         data = HDiscdata
)

m2 = interactionR_boot(m,
                       ci.level = 0.95, em = FALSE, recode = FALSE,
                       seed = 12345, s = 1000
)

interactionR_table(m2)

```

**Comment by jddly** [comment]
Dear friend
Thank you very much for your kind information.
I will use the code to try again.
Really appreciate your kindness.
Have a nice day!

Yours sincerely
Jiao

epi-zen ***@***.***> 于2022年2月5日周六 06:29写道：
